Submitted By -: 
Sanidhya Vishnoi (<sanidhyavishnoi29@gmail.com>)

# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
from scipy import stats 
import numpy as np


In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

### Answer:

In [3]:
stats.ttest_1samp(GPU1,0)

Ttest_1sampResult(statistic=34.056241516158195, pvalue=7.228892044970457e-15)

As P-value < 0.05 , we reject null hypothesis. Accepting alternate , mean is not equal to zero.

## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

### Answer:

In [4]:
stats.ttest_ind(GPU1,GPU2)

Ttest_indResult(statistic=-2.627629513471839, pvalue=0.013794282041452725)

As P-value < 0.05 , we reject null hypothesis. Accepting alternate , there is a significant difference.

## Question 3

He is trying a third GPU - GPU3.

In [5]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

### Answer:

In [6]:
stats.ttest_ind(GPU1,GPU3)

Ttest_indResult(statistic=-1.4988943759093303, pvalue=0.14509210993138993)

As P-value > 0.05 , we failed to reject null hypothesis. There is no significant difference.

## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [7]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

### Answer:

In [8]:
stats.levene(e1,e2,e3)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

As P-value > 0.05 , we failed to reject null hypothesis.

## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

### Answer:

In [9]:
stats.f_oneway(e1,e2,e3)

F_onewayResult(statistic=2.51357622845924, pvalue=0.13574644501798466)

As P-value > 0.05 , we failed to reject null hypothesis.

## Question 6 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.



### Answer:

Null Hypothesis : The mean waiting time remain unchanged at 4.5

Alternate Hypothesis  : The mean waiting time changed from 4.5

## Chi square test

## Question 7

Let's create a small dataset for dice rolls of four players

In [10]:
import numpy as np

d1 = [1, 6, 3, 4]
d2 = [2, 5, 1, 3]
d3 = [4, 2, 3, 1]
d4 = [3, 4, 1, 2]
d5 = [1, 6, 3, 5]
d6 = [3, 2, 2, 1]

dice = np.array([d1, d2, d3, d4, d5, d6])
dice

array([[1, 6, 3, 4],
       [2, 5, 1, 3],
       [4, 2, 3, 1],
       [3, 4, 1, 2],
       [1, 6, 3, 5],
       [3, 2, 2, 1]])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value




### Answer

In [11]:
from scipy.stats import chi2_contingency

chi2 , p ,dof ,ex = chi2_contingency(dice)
print('Chi-square value : ',chi2)
print('P-Value : ',p)

Chi-square value :  11.445004959326388
P-Value :  0.720458335452983


As P-value > 0.01 , we failed to reject null hypothesis.

## Question 8

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

### Answer

In [12]:
dice_z = stats.zscore(dice)
dice_z

array([[-1.20604538,  1.09454091,  0.92847669,  0.89442719],
       [-0.30151134,  0.4975186 , -1.29986737,  0.2236068 ],
       [ 1.50755672, -1.29354835,  0.92847669, -1.11803399],
       [ 0.60302269, -0.09950372, -1.29986737, -0.4472136 ],
       [-1.20604538,  1.09454091,  0.92847669,  1.56524758],
       [ 0.60302269, -1.29354835, -0.18569534, -1.11803399]])

In [13]:
p_value = stats.norm.sf(abs(dice_z))
p_value

array([[0.1139    , 0.13685891, 0.17658018, 0.18554668],
       [0.3815123 , 0.3094117 , 0.09682322, 0.41153164],
       [0.06583401, 0.09791074, 0.17658018, 0.13177624],
       [0.2732468 , 0.46036917, 0.09682322, 0.32736042],
       [0.1139    , 0.13685891, 0.17658018, 0.05876243],
       [0.2732468 , 0.09791074, 0.42634184, 0.13177624]])

In [14]:
p_mean = p_value.mean()
print('P-value : ',p_mean)

P-value :  0.20239343794918715


## Question 9

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [15]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

### Answer

In [16]:
stats.ttest_rel(before,after)

Ttest_relResult(statistic=5.926307270367952, pvalue=5.782667511592146e-09)

As P-value < 0.05 , we reject null hypothesis.